ENH: Automate deploy to PyPI
InsightSoftwareConsortium/itk-dreg pull request #25
Opened 2023-11-15 20:45 UTC by tbirdso

Automatically deploys wheels to the Python Package Index on tag.

Closes https://github.com/InsightSoftwareConsortium/itk-dreg/issues/9

2023-11-15 20:53 UTC, tbirdso commented
@thewtex Would you please create a PyPI access token and add it as a `itk-dreg` repository secret? https://itkpythonpackage.readthedocs.io/en/master/Build_ITK_Module_Python_packages.html?highlight=twine#automate-pypi-package-uploads

2023-11-16 19:36 UTC, thewtex requested changes
@tbirdso thanks!

A few notes inline to transition to enable Trusted Publishing instead of using token / secrets, which is modern / preferred. We could not enable this in the [ITK Remote Module Action yet because Trusted Publishing is not supported in reusable workflows](https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/issues/68).

2023-11-16 19:59 UTC, tbirdso commented
Hi @thewtex , I do not see your suggested changes on the PR?

2023-11-16 20:03 UTC, thewtex commented on .github/workflows/build-test-publish.yml
> +        password: ${{ secrets.pypi_password }}
@tbirdso I added [Trusted Publishing](https://github.com/pypa/gh-action-pypi-publish) support on PyPI, so this should be removed.

but we should also add:

```
    environment:
      name: pypi
      url: https://pypi.org/p/<your-pypi-project-name>
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
```
```suggestion
```

2023-11-16 20:07 UTC, thewtex commented
@tbirdso sorry, not sure what happened -- added as a Single Comment.

2023-11-16 20:45 UTC, tbirdso commented on .github/workflows/build-test-publish.yml
> +        password: ${{ secrets.pypi_password }}
Great! Good to know. I've pushed a commit with the requested changes.

2023-11-16 20:47 UTC, tbirdso commented
@thewtex Pushed a last commit on my way out the door, feel free to push to my dev branch if there are other changes required to get this through. Thanks!

2023-11-17 17:15 UTC, thewtex approved these changes
:rocket:

2023-11-17 17:15 UTC, merged